# Generated by Django 4.0.1 on 2022-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('id_news', models.IntegerField(default=None, null=True)),
                ('time', models.IntegerField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('type', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('id_news', models.IntegerField(default=None, null=True)),
                ('time', models.IntegerField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('type', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('id_news', models.IntegerField(default=None, null=True)),
                ('time', models.IntegerField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('type', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(default=None, null=True)),
                ('id_news', models.IntegerField(default=None, null=True)),
                ('time', models.IntegerField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('type', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
            ],
        ),
    ]
